# Generated by Django 5.1.7 on 2025-03-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_id', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='user id')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Cure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Лекарство')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Вреям начала приема')),
                ('frequency', models.PositiveIntegerField(verbose_name='Периодичность приема')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cure', to='api.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лекарство',
                'verbose_name_plural': 'Лекарства',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField(verbose_name='Дата и время приема')),
                ('cure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='api.cure', verbose_name='Лекарство')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['reminder_time'],
            },
        ),
    ]
