# Generated by Django 5.1.7 on 2025-03-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cure',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продолжительность'),
        ),
    ]
